name: Build Docker Image

on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ release/* ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    # needs: unit-tests
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: 'type=registry,ref=${{ steps.meta.outputs.tags }}-buildcache'
          cache-to: 'type=registry,ref=${{ steps.meta.outputs.tags }}-buildcache,mode=max'

      # - name: Invoke deployment hook
      #   uses: distributhor/workflow-webhook@v2
      #   env:
      #     webhook_url: ${{ secrets.WEBHOOK_URL }}
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      #     data: '{ "link": "${{ github.repositoryUrl	 }}", "status" : "${{ job.status }}" }'